OBJ = board.o player.o deck.o tiles.o

capitalism: $(OBJ)
	gcc -o capitalism $(OBJ)

board.o: board.c
	gcc -c board.c

player.o: player.c
	gcc -c player.c

deck.o: deck.c
	gcc -c deck.c

Tiles.o: tiles.c
	gcc -c tiles.c